***
Hi and welcome to this Python basics course! 
<br>
<br>
This crash course will serve as an introduction for courses where we will use python as our programming language and will be a way for you to get introduced into it.
***

### Numpy

NumPy is a Python library for numerical computing that provides efficient and convenient array operations and linear algebra routines.
<br>
<br>
Numpy is an external library widely used to deal with arrays, matrixes and tensors in Python - this is an external library so we have to import it to be able to use its functions:

In [1]:
import numpy as np

A simple one dimensional array:

In [2]:
np.array(1)

array(1)

A one dimensional array with two elements:

In [3]:
np.array([1,2])

array([1, 2])

A two dimensional array:

In [4]:
np.array([[1,2],[2,3]])

array([[1, 2],
       [2, 3]])

We can check dimensions using the shape attribute:

In [5]:
np.array([[1,2],[2,3]]).shape

(2, 2)

`Numpy zeros` and `numpy ones` create arrays of 0's or 1's with a specific shape:

In [6]:
np.zeros([1,2])

array([[0., 0.]])

Arrays do not stop at 2 dimensions!

In [7]:
np.zeros([1,2,4]).shape

(1, 2, 4)

In [8]:
np.ones([1,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

We can access numpy arrays like we access other python objects such as lists:

In [9]:
example_array = np.array([[1,2],[3,4]])

The only difference is that we are now indexing multi-dimensional objects using `,`:

In [15]:
example_array[1,1]

4

In [16]:
example_array[1,0]

3

In [17]:
example_array[0,1]

2

In [14]:
example_array[0,0]

1

### Pandas

Pandas is a Python library for data manipulation and analysis that provides powerful data structures, such as dataframes and series, and a variety of functions and methods for handling and processing data.

In [18]:
import pandas as pd

In [19]:
pd.DataFrame(np.array([0,1,2]), columns=['col'], index=['A','B','C'])

col
A    0
B    1
C    2

We can also pass lists when creating DataFrames:

In [20]:
pd.DataFrame([[0,1,2],[1,2,3]], columns=['col_1', 'col_2','col_3'], index=['A','B'])

col_1  col_2  col_3
A      0      1      2
B      1      2      3

In [21]:
dataframe_example = (
    pd.DataFrame([[0,'A',2],[1,'B',3]], columns=['col_1', 'col_2','col_3'], index=['A','B'])
)

To index dataframes we can use names or indexes (using either `loc` or `iloc`):

In [22]:
dataframe_example.loc[:,'col_1']

A    0
B    1
Name: col_1, dtype: int64

In [23]:
dataframe_example.iloc[:,0]

A    0
B    1
Name: col_1, dtype: int64

In [24]:
dataframe_example.loc['A',:]

col_1    0
col_2    A
col_3    2
Name: A, dtype: object

In [25]:
dataframe_example.iloc[0,:]

col_1    0
col_2    A
col_3    2
Name: A, dtype: object